### ISSUE TITLE
Recently completed audits tiles inconsistent heights

### ISSUE THREAD

**Issue by SamusElderg** [code4rena-dev/components-library#33]
Moved here from: https://github.com/code4rena-dev/code4rena.com/issues/684 will need to also do a PR over there afterwards to point to the new comp-lib version

-------------------

For the not-logged-in view on the home page, each tile can have different heights

Currently:
![image](https://github.com/code4rena-dev/code4rena.com/assets/26967164/423d0eaf-19f6-475b-a54f-061c3cd791e2)

Aim to make it something like this:
![image](https://github.com/code4rena-dev/code4rena.com/assets/26967164/2ea9a026-927a-41de-aa8c-524ffc79e1d5)

Would need to be conscious of two areas (if we used fixed heights to solve it):
- The title of the contest (this would/could be expected to be 1 or 2 lines in most situations, so probably fixed at 2 lines with ellipses for any extra)
- The blurb under the title (this should be probably fixed at 3 lines with any extra text being cut off with ellipses)

**Comment by SamusElderg** [comment]
Will move this back, looks like its not a component-library component 😂

**Comment by SamusElderg** [comment]
Re-opening because i am an airhead

**Comment by leo95oliveira** [comment]
This was resolved in this PR: https://github.com/code4rena-dev/components-library/pull/42
and will be resolved in the front-end by this PR: https://github.com/code4rena-dev/code4rena.com/pull/730
