### ISSUE TITLE
Doesn't include react toastify as a dependency and probably should

### ISSUE THREAD

**Issue by sockdrawermoney** [code4rena-dev/components-library#80]
Got this when playing with this in another project:

`Module not found: Can't resolve 'react-toastify/dist/ReactToastify.min.css'`

**Comment by SamusElderg** [comment]
> Got this when playing with this in another project:
> 
> `Module not found: Can't resolve 'react-toastify/dist/ReactToastify.min.css'`

Might need to include it in the consumer, its definitely in the component library, id try the following:
- delete the node_modules folder
- make sure the component library version being used in the project is at least v4.3.1
- run a fresh `npm install`

See if the issue persist after that, if it does, we'd just have to make a note in the readme of this to make sure consumers include the css file somewhere in their app

**Comment by SamusElderg** [comment]
> Got this when playing with this in another project:
> 
> `Module not found: Can't resolve 'react-toastify/dist/ReactToastify.min.css'`

Deleted my previous replie/s 😂 -- the component library doesnt use toasts at all as far as im aware, so this will trace back to something else being the source of the problem in the project you are working on but the following should fix it:

- add the following import in ideally the main css file in the project:
`@import "react-toastify/dist/ReactToastify.min.css";`

**Comment by sockdrawermoney** [comment]
Yeah I was not using toasts, so this was just a weird error to get. I assumed it was the component library, but guess not!
